Update 0-transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-# check if parameters are lest than 4
+# Check if parameters are lest than 4
 if [ $# -lt 4 ]
 then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-	exit 1
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
 fi
 
 # Variables assiged to paremeters
@@ -13,14 +13,14 @@ ip=$2
 username=$3
 path_to_ssh_key=$4
 
-# disable strict host checking
 
-scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@ip:~/"
+# Disable strict host checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
 
-#checking if the transfer was successful
+# Checking if the transfer was successful
 if [ $? -eq 0 ]
 then
-	echo "File transfered successfully"
+  echo "FILE TRANSFER WAS SUCCESSFULL"
 else
-	echo "File tranfer failed"
+  echo "FILE TRANSFER FAILED"
 fi
